name: Monthly PP Reset

on:
  schedule:
    - cron: '0 17 30,31 * *' # 17:00 UTC = 00:00 WIB (jam reset PP)
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  reset-pp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Reset Script
        run: node reset.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Reset PP for new month"
          git push
